### ISSUE TITLE
Update pong example to reflect changes to crystal

### ISSUE THREAD

**Issue by gnations56** [meew0/discordcr#135]
in the ping example, the require line no longer works.
I have gotten this require to work: require "../lib/discordcr/src/discordcr"
the change in shard install location is detailed in issue #3897 on the crystal github repo

**Comment by z64** [comment]
The examples in this repo have `require "../src/discordcr"` because they are compiled with the library itself as part of our CI, `.travis.yml`:
```yaml
  - find examples -name "*.cr" | xargs -L 1 crystal build --no-codegen
```
That is, they are not examples you can copy/paste and just have work. You must change `require "../src/discordcr"` to `require "discordcr"` yourself. It's done the way it is so that our testing service (Travis CI) will tell us if we do something to break those examples.

**Comment by RX14** [comment]
indeed, `require "discordcr"` is all you need here.

Maybe we should fudge `CRYSTAL_PATH` in the CI to make these compile anyway though.

**Comment by gnations56** [comment]
ok because when i just tried discordcr, crystal could not find it
